# Generated by Django 3.2.3 on 2021-06-14 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentalOperation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FilePathField(path='/userImg')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FundamentalOperation.user')),
            ],
        ),
    ]
