# Generated by Django 3.2.3 on 2021-06-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentalOperation', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(default='null', upload_to='img'),
        ),
    ]
