# Generated by Django 3.2.3 on 2021-06-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentalOperation', '0003_image_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
