# Generated by Django 3.2.3 on 2021-06-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentalOperation', '0005_document_music_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.AddField(
            model_name='image',
            name='url',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='music',
            name='singer_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='music',
            name='song_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='video_name',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='music',
            name='url',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
