# Generated by Django 3.2.3 on 2021-06-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FundamentalOperation', '0006_auto_20210615_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.TextField(default='#'),
        ),
    ]
